
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        wordCountLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        countButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        sentenceCountLabel = new javax.swing.JLabel();
        paragraphCountLabel = new javax.swing.JLabel();
        searchResultLabel = new javax.swing.JLabel();
        charCountLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("APLIKASI PENGHITUNG KATA");

        saveButton.setText("Simpan ke File");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        wordCountLabel.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        wordCountLabel.setText("Kata :");

        jLabel3.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel3.setText("Cari Kata");

        countButton.setText("Hitung");
        countButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Cari");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        sentenceCountLabel.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        sentenceCountLabel.setText("Kalimat :");

        paragraphCountLabel.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        paragraphCountLabel.setText("Paragraf :");

        searchResultLabel.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        searchResultLabel.setText("Hasil Pencarian");

        charCountLabel.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        charCountLabel.setText("Huruf :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(countButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(wordCountLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(132, 132, 132))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paragraphCountLabel)
                            .addComponent(sentenceCountLabel)
                            .addComponent(charCountLabel))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(searchResultLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(searchField)
                                .addGap(18, 18, 18)
                                .addComponent(searchButton)))
                        .addGap(131, 131, 131))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(searchButton))
                .addGap(18, 18, 18)
                .addComponent(searchResultLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countButton)
                    .addComponent(saveButton))
                .addGap(21, 21, 21)
                .addComponent(wordCountLabel)
                .addGap(18, 18, 18)
                .addComponent(charCountLabel)
                .addGap(18, 18, 18)
                .addComponent(sentenceCountLabel)
                .addGap(18, 18, 18)
                .addComponent(paragraphCountLabel)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void countButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countButtonActionPerformed
updateCounts();
        // TODO add your handling code here:
    }//GEN-LAST:event_countButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
String word = searchField.getText();
int wordOccurrence = countSpecificWord(word);
searchResultLabel.setText("Hasil Pencarian: " + wordOccurrence);
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
saveToFile();
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed
private void updateCounts() {
    String text = textArea.getText();
    wordCountLabel.setText("Jumlah Kata: " + countWords(text));
    charCountLabel.setText("Jumlah Karakter: " + countCharacters(text));
    sentenceCountLabel.setText("Jumlah Kalimat: " + countSentences(text));
    paragraphCountLabel.setText("Jumlah Paragraf: " + countParagraphs(text));
}

private int countWords(String text) {
    String[] words = text.trim().split("\\s+");
    return words.length;
}

private int countCharacters(String text) {
    return text.replaceAll("\\s+", "").length();
}

private int countSentences(String text) {
    String[] sentences = text.split("[.!?]");
    return sentences.length;
}

private int countParagraphs(String text) {
    String[] paragraphs = text.split("\\n+");
    return paragraphs.length;
}

private int countSpecificWord(String word) {
    String text = textArea.getText();
    int count = 0;
    String[] words = text.split("\\s+");
    for (String w : words) {
        if (w.equalsIgnoreCase(word)) {
            count++;
        }
    }
    return count;
}

private void saveToFile() {
    try (FileWriter writer = new FileWriter("hasil_penghitungan.txt")) {
        writer.write("Jumlah Kata: " + countWords(textArea.getText()) + "\n");
        writer.write("Jumlah Karakter: " + countCharacters(textArea.getText()) + "\n");
        writer.write("Jumlah Kalimat: " + countSentences(textArea.getText()) + "\n");
        writer.write("Jumlah Paragraf: " + countParagraphs(textArea.getText()) + "\n");
        writer.write("Konten Teks:\n" + textArea.getText());
        JOptionPane.showMessageDialog(this, "Hasil disimpan ke file.");
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan ke file.");
    }
}
private void start(){
    textArea.getDocument().addDocumentListener(new DocumentListener() {
    
    public void insertUpdate(DocumentEvent e) { updateCounts(); }
    
    public void removeUpdate(DocumentEvent e) { updateCounts(); }
   
    public void changedUpdate(DocumentEvent e) { updateCounts(); }
});

}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel charCountLabel;
    private javax.swing.JButton countButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel paragraphCountLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel searchResultLabel;
    private javax.swing.JLabel sentenceCountLabel;
    private javax.swing.JTextArea textArea;
    private javax.swing.JLabel wordCountLabel;
    // End of variables declaration//GEN-END:variables
}
